name: Go Lint Codebase

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up Go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: 1.23

      - name: Install linter
        run: go install golang.org/x/lint/golint@latest

      - name: Run linter
        run: golint ./...

